# Generated by Django 5.2.17 on 2026-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(help_text='e.g. Toyota Innova Crysta', max_length=120)),
                ('registration_number', models.CharField(help_text='e.g. OD 02 AB 1234', max_length=30, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Van', 'Van / Traveller')], default='Sedan', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=4, help_text='Passenger seating capacity')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], default='Petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=20)),
                ('ac', models.BooleanField(default=True, verbose_name='Air Conditioned')),
                ('luggage_capacity', models.CharField(blank=True, default='3 bags', max_length=50)),
                ('per_day_rate', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Trip', 'On Trip'), ('Maintenance', 'Maintenance / In Service'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
                ('insurance_info', models.CharField(blank=True, max_length=150)),
                ('permit_info', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
