# Generated by Django 5.2.17 on 2026-10-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(help_text='e.g. DRV001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On Duty', 'On Duty'), ('On Leave', 'On Leave'), ('Inactive', 'Inactive')], default='Available', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['driver_id'],
            },
        ),
    ]
